apiVersion: v1
kind: Service
metadata:
  name: jlove-pod-service
  namespace: rashid
  labels:
    owner: jlove
spec:
  selector: 
    owner: jlove-pod
    app: ssh
  ports:
  - port: 9050
    targetPort: 22
    nodePort: 30050
    name: ssh-port
  type: NodePort